"""producao

Revision ID: 11858e68667b
Revises: 9496917eba3e
Create Date: 2025-12-08 11:11:16.156085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11858e68667b'
down_revision = '9496917eba3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('honorario', sa.Float(), nullable=True))
        batch_op.drop_column('id_user_recebeu_nao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_recebeu_nao', sa.INTEGER(), nullable=True))
        batch_op.drop_column('honorario')

    # ### end Alembic commands ###
