"""endereco

Revision ID: fba36c9c1746
Revises: 82e3020bfee2
Create Date: 2025-11-26 22:39:59.977151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba36c9c1746'
down_revision = '82e3020bfee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_enderecos')
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rua', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('bairro')
        batch_op.drop_column('cep')
        batch_op.drop_column('rua')

    op.create_table('_alembic_tmp_enderecos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=300), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('rua', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=50), nullable=False),
    sa.Column('bairro', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
