"""coluna no Placa 

Revision ID: 05183e87abeb
Revises: e8aaef70ac8b
Create Date: 2025-07-27 22:47:15.068138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05183e87abeb'
down_revision = 'e8aaef70ac8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_recebeu', sa.Integer()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.drop_column('id_user_recebeu')

    # ### end Alembic commands ###
