"""cascade

Revision ID: 0b457d61a52b
Revises: 17dd6b78be3a
Create Date: 2025-10-06 21:52:33.791631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b457d61a52b'
down_revision = '17dd6b78be3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_recebeu_', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.drop_column('id_user_recebeu_')

    # ### end Alembic commands ###
