"""inicio

Revision ID: 0d94f8ff2df3
Revises: 
Create Date: 2025-09-14 12:59:34.320516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d94f8ff2df3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pagamento', sa.String(length=100), nullable=False),
    sa.Column('status_pagamento', sa.String(length=50), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('valor_transacao', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('renavan', sa.String(length=20), nullable=True),
    sa.Column('endereco_placa', sa.String(length=100), nullable=False),
    sa.Column('crlv', sa.String(length=20), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('placa_confeccionada', sa.Boolean(), nullable=True),
    sa.Column('placa_a_caminho', sa.Boolean(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_user_recebeu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=20), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_placa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_placa'], ['placas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_file')
    op.drop_table('placas')
    op.drop_table('pagamentos')
    op.drop_table('enderecos')
    op.drop_table('users')
    # ### end Alembic commands ###
