"""coluna de senha deletada

Revision ID: 19a18594d2ab
Revises: 22a308199973
Create Date: 2026-01-18 16:13:25.552309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a18594d2ab'
down_revision = '22a308199973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store_agente')
    op.drop_table('message_store')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('rg',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('rg',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_pkey')
    )
    op.create_table('message_store_agente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_agente_pkey')
    )
    # ### end Alembic commands ###
