"""cascade cpl

Revision ID: 20197fe67cd2
Revises: 28f5a5b73596
Create Date: 2025-10-06 22:25:08.049059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20197fe67cd2'
down_revision = '28f5a5b73596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_recebeu_nao', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.drop_column('id_user_recebeu_nao')

    # ### end Alembic commands ###
