"""cascade cpl

Revision ID: 28f5a5b73596
Revises: 0b457d61a52b
Create Date: 2025-10-06 22:01:52.414294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f5a5b73596'
down_revision = '0b457d61a52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.drop_column('id_user_recebeu_')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_recebeu_', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
