"""coluna chassi

Revision ID: 84701099a5af
Revises: 0d94f8ff2df3
Create Date: 2025-09-16 20:01:22.119410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84701099a5af'
down_revision = '0d94f8ff2df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chassi', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.drop_column('chassi')

    # ### end Alembic commands ###
