"""rg cpf

Revision ID: 860fba61a2e6
Revises: 20197fe67cd2
Create Date: 2025-11-26 19:55:50.273380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860fba61a2e6'
down_revision = '20197fe67cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store_agente')
    op.drop_table('message_store')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rg')
        batch_op.drop_column('cpf_cnpj')

    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_pkey')
    )
    op.create_table('message_store_agente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_agente_pkey')
    )
    # ### end Alembic commands ###
