"""update

Revision ID: 8c9c78c5ed17
Revises: d0f686ab9db8
Create Date: 2025-12-10 18:13:46.110784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9c78c5ed17'
down_revision = 'd0f686ab9db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store')
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('honorario', sa.Float(), nullable=True))
        batch_op.drop_column('id_user_recebeu_nao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user_recebeu_nao', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('honorario')

    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_pkey')
    )
    # ### end Alembic commands ###
