"""float

Revision ID: bce955fb0f53
Revises: 05183e87abeb
Create Date: 2025-07-29 21:21:09.469454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce955fb0f53'
down_revision = '05183e87abeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_transacao', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('valor_transacao')

    # ### end Alembic commands ###
