"""colunas_chave_data

Revision ID: df76f83b821b
Revises: 19a18594d2ab
Create Date: 2026-02-04 08:46:58.469314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df76f83b821b'
down_revision = '19a18594d2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store')
    op.drop_table('message_store_agente')
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_acesso', sa.String(length=400), nullable=False))
        batch_op.add_column(sa.Column('data_emissao_nf', sa.String(length=10), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.drop_column('data_emissao_nf')
        batch_op.drop_column('chave_acesso')

    op.create_table('message_store_agente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_agente_pkey')
    )
    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_pkey')
    )
    # ### end Alembic commands ###
