"""nome proprietario

Revision ID: faf70967b7d4
Revises: 8c9c78c5ed17
Create Date: 2025-12-24 23:21:04.996356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf70967b7d4'
down_revision = '8c9c78c5ed17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boletos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('id_placa', sa.Integer(), nullable=False),
    sa.Column('fk_boleto_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_boleto_usuario'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_placa'], ['placas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_boleto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_boleto'], ['boletos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_store')
    op.drop_table('message_store_agente')
    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_proprietario', sa.String(length=40), nullable=True))
        batch_op.alter_column('honorario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('placas', schema=None) as batch_op:
        batch_op.alter_column('honorario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('nome_proprietario')

    op.create_table('message_store_agente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_agente_pkey')
    )
    op.create_table('message_store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_store_pkey')
    )
    op.drop_table('taxas')
    op.drop_table('boletos')
    # ### end Alembic commands ###
