"""rg cpf cnpj

Revision ID: 82e3020bfee2
Revises: 1f816fa1ac7b
Create Date: 2025-11-25 22:12:59.015871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e3020bfee2'
down_revision = '1f816fa1ac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rg')
        batch_op.drop_column('cpf_cnpj')

    # ### end Alembic commands ###
