"""cidade uf

Revision ID: e68a8fe01fdd
Revises: fba36c9c1746
Create Date: 2025-11-26 22:47:24.318180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68a8fe01fdd'
down_revision = 'fba36c9c1746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
